FROM node:20

WORKDIR /app

# Copy pre-built code
COPY dist ./dist
COPY node_modules ./node_modules
COPY package*.json ./
COPY prisma ./prisma

# Regenerate Prisma client for this platform
RUN npx prisma generate

EXPOSE 3000

CMD ["node", "dist/src/main.js"]
